### PR TITLE
fixes #833

### LINKED ISSUE #833: Vert.x name appears within Spring Boot SSO Booster instructions
Vertx-admin name appears within Spring Boot SSO Booster instructions

screenshot 2017-11-08 18 26 14

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by Ladicek** [comment]
I think this is wrong. We no longer have one role per each runtime, but a single role for all of them, called `booster-admin`. Also see #834.

**Comment by rhoads-zach** [comment]
@Ladicek thanks for the feedback. Let me know what you think of the updates

**Comment by rhoads-zach** [comment]
merging.

**Comment by rhoads-zach** [comment]
merged: b8d68ac378ffa7a05a28bf36f437fe7b3184ffbf

**Comment by Ladicek** [comment]
No more issues, LGTM (post facto) :-)

**Pull request closed without merging**
