### PR TITLE
WIP - DO NOT MERGE: Fixes #912: update WFS version

### LINKED ISSUE #912: WildFly Swarm guide: missing product version number
The Swarm guide doesn't tell what's the version number to use when adding Maven dependencies. What's more, when showing the BOM usage, it even uses a community version number for demonstration!

FTR, the correct version number for our first GA is `7.0.0.redhat-8`.

### PR DESCRIPTION
**Pull request by inoxx03**
@Ladicek I've updated the WildFly Swarm version attribute to show the Productized version. WDYT?

### CODE REVIEW

**Comment by Ladicek** [comment]
This is wrong IMHO. One, it doesn't affect the WildFly Swarm guide, and two, it's used in URLs to Swarm community docs.

**Comment by inoxx03** [comment]
@Ladicek I believe the change does indeed affect the WildFly Swarm guide (Specifically the chapter that deals with using the BOM). The version displayed in the guide is sourced from the variable that has been changed.

I have completely missed the URLs, though, so thank you for pointing that out:) I'll fix those and update the PR.

**Comment by Ladicek** [comment]
I think this breaks the rules of how WildFly Swarm docs should be updated, but is OK for now. @tradej will need to fix this properly when he returns :-)

**Comment by rhoads-zach** [comment]
thanks @Ladicek.
merging

**Comment by rhoads-zach** [comment]
merged: 999fc44ec7a6e3dc2b63d8b84b284d19f9c7e94f

**Comment by inoxx03** [comment]
@lthon Thank you:) FTR, I'd personally be more comfortable letting Sheldon handle this, too... But as an emergency fix, I hope this'll do:)

**Comment by tradej** [comment]
Hi, just to confirm, I believe this fix is perfectly fine and can stay as a permanent one. We both want the product version (now stored in `WildFlySwarmProductVersion`) and the community version (now stored in `WildFlySwarmVersion`, but it can be renamed to, say, `WildFlySwarmCommunityVersion`).

As for the rules of updating, since no files in `docs/topics/wildfly-swarm` were changed, this PR is 100% by the book.

As for setting the WFS product version in `document-attributes.adoc`, I'm afraid we'll have to do it because we can not reproduce a WFS product build completely (setting the version happens there), so this is acceptable.

**Comment by Ladicek** [comment]
I knew there is a directory with `wildfly-swarm` in the name that must not be updated manually, and probably some brain hiccup caused me to believe that this PR did that. Happy to have been wrong :-)

**Comment by tradej** [comment]
I appreciate you remembered that; it's better than if it was forgotten. :)

**Pull request closed without merging**
