### PR TITLE
GSG: Minishift & CDK version update

### LINKED ISSUE #707: Update Minishift and CDK versions
The Minishift version in the docs is currently listed as `1.5.0`,
CDK version is listed as `3.0.0`.
AFAIK, this is no longer true, as we have moved to  CDK version `3.1.1`.
We are also currently using Minishift version `1.7.0`.

resolved in PR #708

### PR DESCRIPTION
**Pull request by inoxx03**
Updated the Minishift and CDK versions:
Minishift: `1.7.0`
CDK: `3.1.1`

@cescoffier Would you know of any currently open issues that would prevent us from updating to these versions?

resolves #707

### CODE REVIEW

**Comment by Ladicek** [comment]
I'd like to request one change -- in the SSO mission docs (which are currently commented out or something, but will likely be coming back), we refer to the CentOS ISO by a full URL, which also contains a version number. Specifically, it's currently 1.0.0 currently. That version of the CentOS ISO has an issue that I was myself affected by. Could we update it to use `--iso-url=centos`? That's a shortcut to "the CentOS ISO version hardcoded into current Minishift version", which for Minishift 1.7.0 is CentOS ISO 1.3.0.

That would be all, LGTM otherwise.

**Comment by inoxx03** [comment]
@Ladicek Thank you for the review:) I've changed the `--iso-url` option to use the `centos` shortcut instead of the full URL.

**Comment by inoxx03** [comment]
@tradej @rhoads-zach please feel free to merge if this looks OK to you.

**Comment by rhoads-zach** [comment]
merged: 9abde2a1bd08bf907b95fb0aedb92aba3c0830f7

**Pull request closed without merging**
