### PR TITLE
add spring architecture and framework refs

### LINKED ISSUE #749: Spring Boot: Update references section
Add links to any new references for SB 1.5.8 and others that may be appropriate for  this guide

### PR DESCRIPTION
**Pull request by lavernw1**
Fixes #749 @rhoads-zach @claprun please review.

### CODE REVIEW

**Comment by rhoads-zach** [comment]
LGTM.

@metacosm thoughts?

**Comment by metacosm** [comment]
Belated 👍

**Comment by rhoads-zach** [comment]
merging.

**Comment by rhoads-zach** [comment]
6279f7a6037ef1e8f18237ba57e1ee43be8a0e44

**Pull request closed without merging**
