### PR TITLE
 Fixes #815 #814 #812 #811 #762 updates

### LINKED ISSUE #815: [spring-boot] Mission introduction is not correct
This text 

```
Missions are working applications that showcase different fundamental pieces of building cloud native applications and services, such as creating HTTP APIs, interoperating with a database, or implementing the health check pattern. A booster is the implementation of a mission in a specific runtime. Boosters are preconfigured, functioning applications based on a mission that demonstrate a fundamental aspect of modern application development running in an environment similar to production. Missions and boosters can be used as a proof of technology demonstration, a teaching tool, or even a sandbox for understanding how to develop applications. They can also be updated or extended for your own use case.
```

should be replaced by

```
Missions are working applications that showcase different fundamental pieces of building cloud native applications (as presented within the concept chapter) and services, such as creating REST, 
interoperating with a database or implementing the health check pattern. The mission can be used as a proof of technology demonstration, a teaching tool, or even a sandbox for understanding how to develop application in order to develop your own project. They can also be updated or extended for your own use case.

NOTE: A booster, by convention, is the implementation of a mission in a specific runtime and by consequent, it will be used within the next sections

```

### PR DESCRIPTION
**Pull request by lavernw1**
Additional updates  for Spring Boot mission, runtime details.  
@metacosm  can you review runtime details in file  docs/spring-boot-runtime/master.adoc for issue 762.

@cmoulliard can you review  both files for  runtime details and mission changes for  issues 815, 814, 812, 811

### CODE REVIEW

**Comment by metacosm** [comment]
LGTM, what do you think @cmoulliard?

**Comment by lavernw1** [comment]
@cmoulliard  thanks for  the review per slack. LGTM can you approve  PR.

**Comment by cmoulliard** [comment]
LGTM too. Go ahead and merge it @lavernw1

**Comment by tradej** [comment]
Merging...

**Comment by tradej** [comment]
merged 05d9aedd9

**Pull request closed without merging**
